[package]
name = "eeprom"
version = "0.1.0"
authors = ["ZennDev <zenndev@protonmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
arduboy-rust = { path = "../../../arduboy-rust" }
